// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjvzkylctprhxxilaeah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqdnpreWxjdHByaHh4aWxhZWFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNjEyODcsImV4cCI6MjA2NzczNzI4N30.1bB0S-ddt5jEmvveBZ2HvlOjTHc6r_KqVT3RymvM574";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});